language: go
go:
  - 1.4
  - 1.5
  - tip

sudo: false

install:
  - go get -t -d -v ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/jteeuwen/go-bindata/...
  - go-bindata -o assets/templates.go -pkg=assets templates/...

script:
  - ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
